[package]
name = "papyrus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
neoglot-lib = {git = "https://github.com/Mkdirs/neoglot-lib.git", branch = "beta"}